"use server";
import{compare,hash}from"bcryptjs";import{redirect}from"next/navigation";import{revalidatePath}from"next/cache";import{db}from"@/lib/db";import{clearSession,requireBusinessWriter,requireOwner,requireUser,setSession}from"@/lib/auth";import{calculateProductionUsage}from"@/lib/production";
import{isValidShipmentItems,type ShipmentItem}from"@/lib/shipment";
const n=(v:FormDataEntryValue|null)=>Number(v);
const go=(tab:string,msg:string)=>{revalidatePath("/");redirect("/?tab="+tab+"&ok="+encodeURIComponent(msg))};
export async function loginAction(f:FormData){const username=String(f.get("username")||"").trim(),password=String(f.get("password")||"");const u=await db.user.findUnique({where:{username}});if(!u||!u.active||!await compare(password,u.passwordHash))redirect("/login?error=1");await setSession(u.id);redirect("/")}
export async function logoutAction(){await clearSession();redirect("/login")}
export async function produceAction(f:FormData){const u=await requireBusinessWriter(),productId=n(f.get("productId")),quantity=n(f.get("quantity"));if(quantity<=0)throw new Error("Количество должно быть больше нуля");await db.$transaction(async tx=>{const p=await tx.product.findUnique({where:{id:productId},include:{recipes:{include:{ingredient:true}}}});if(!p||!p.recipes.length)throw new Error("У продукта нет рецептуры");const usage=calculateProductionUsage(p.recipes.map(r=>({ingredientId:r.ingredientId,quantity:r.quantity,stock:r.ingredient.stock})),quantity);for(const item of usage){await tx.ingredient.update({where:{id:item.ingredientId},data:{stock:{decrement:item.used}}});await tx.ingredientMovement.create({data:{ingredientId:item.ingredientId,type:"PRODUCTION_USE",quantity:-item.used,note:"Партия "+p.name}})}await tx.productStock.upsert({where:{productId},create:{productId,quantity},update:{quantity:{increment:quantity}}});await tx.productionBatch.create({data:{productId,quantity,userId:u.id,note:String(f.get("note")||"")}})});go("production","Партия выпущена, сырьё списано")}
export async function shipmentAction(f:FormData){
 const u=await requireBusinessWriter(),customerId=n(f.get("customerId")),paid=n(f.get("paid"));
 let items:unknown=[];
 try{items=JSON.parse(String(f.get("items")||"[]"))}catch{throw new Error("Не удалось прочитать состав отгрузки")}
 if(!isValidShipmentItems(items))throw new Error("Добавьте продукцию и количество");
 const shipmentItems:ShipmentItem[]=items;
 if(new Set(shipmentItems.map(i=>i.productId)).size!==shipmentItems.length)throw new Error("Одинаковая продукция добавлена дважды");
 await db.$transaction(async tx=>{
  const ids=shipmentItems.map(i=>i.productId),products=await tx.product.findMany({where:{id:{in:ids},active:true},include:{stock:true}});
  if(products.length!==shipmentItems.length)throw new Error("Одна из позиций недоступна");
  let total=0;for(const item of shipmentItems){const p=products.find(x=>x.id===item.productId)!;if(!p.stock||p.stock.quantity<item.quantity)throw new Error("Недостаточно на складе: "+p.name);total+=p.price*item.quantity}
  if(paid<0||paid>total)throw new Error("Проверьте сумму оплаты");
  const s=await tx.shipment.create({data:{customerId,userId:u.id,total,paidAmount:paid,status:"DELIVERED",note:String(f.get("note")||""),items:{create:shipmentItems.map(item=>{const p=products.find(x=>x.id===item.productId)!;return{productId:item.productId,quantity:item.quantity,price:p.price,costPrice:p.costPrice}})}}});
  for(const item of shipmentItems){await tx.productStock.update({where:{productId:item.productId},data:{quantity:{decrement:item.quantity}}});await tx.productMovement.create({data:{productId:item.productId,type:"SHIPMENT",quantity:-item.quantity,userId:u.id,shipmentId:s.id,note:"Отгрузка №"+s.id}})}
  if(paid>0)await tx.payment.create({data:{customerId,shipmentId:s.id,amount:paid,method:String(f.get("method"))==="TRANSFER"?"TRANSFER":"CASH"}});
  await tx.customer.update({where:{id:customerId},data:{bonusPoints:{increment:Math.floor(total/10)}}})
 });go("shipments","Отгрузка сохранена")
}export async function openingDebtAction(f:FormData){
 await requireOwner();const customerId=n(f.get("customerId")),amount=n(f.get("amount")),note=String(f.get("note")||"Начальный долг"),rawDate=String(f.get("debtDate")||""),debtDate=rawDate?new Date(rawDate+"T12:00:00"):new Date();
 if(amount<=0||Number.isNaN(debtDate.getTime()))throw new Error("Проверьте сумму и дату долга");
 await db.customerDebt.create({data:{customerId,amount,debtDate,note}});go("customers","Начальный долг клиента добавлен")
}export async function paymentAction(f:FormData){
 await requireOwner();const customerId=n(f.get("customerId")),amount=n(f.get("amount")),method=String(f.get("method"))==="TRANSFER"?"TRANSFER" as const:"CASH" as const,note=String(f.get("note")||"");
 if(amount<=0)throw new Error("Введите сумму");
 await db.$transaction(async tx=>{let left=amount;
  const debts=await tx.customerDebt.findMany({where:{customerId},orderBy:{debtDate:"asc"}});
  for(const d of debts){if(left<=0)break;const due=Math.max(0,d.amount-d.paidAmount);if(!due)continue;const part=Math.min(due,left);await tx.customerDebt.update({where:{id:d.id},data:{paidAmount:{increment:part}}});await tx.payment.create({data:{customerId,customerDebtId:d.id,amount:part,method,note}});left-=part}
  const open=await tx.shipment.findMany({where:{customerId,status:"DELIVERED"},orderBy:{deliveredAt:"asc"}});
  for(const s of open){if(left<=0)break;const due=Math.max(0,s.total-s.paidAmount);if(!due)continue;const part=Math.min(due,left);await tx.shipment.update({where:{id:s.id},data:{paidAmount:{increment:part}}});await tx.payment.create({data:{customerId,shipmentId:s.id,amount:part,method,note}});left-=part}
  if(left>0)await tx.payment.create({data:{customerId,amount:left,method,note:note||"Аванс"}})
 });go("finance","Оплата распределена: сначала старый долг, затем накладные")
}export async function laborExpenseAction(f:FormData){const u=await requireOwner(),amount=n(f.get("amount")),workerName=String(f.get("workerName")||"").trim(),rawDate=String(f.get("workDate")||""),spentAt=rawDate?new Date(rawDate+"T12:00:00"):new Date(),details=String(f.get("note")||"").trim();if(!workerName||amount<=0||Number.isNaN(spentAt.getTime()))throw new Error("Укажите работника, дату и сумму");await db.expense.create({data:{category:"Оплата работников",amount,spentAt,note:workerName+(details?" · "+details:""),userId:u.id}});go("finance","Оплата работнику записана в расходы")
}export async function expenseAction(f:FormData){const u=await requireOwner(),amount=n(f.get("amount"));if(amount<=0)throw new Error("Введите сумму");await db.expense.create({data:{category:String(f.get("category")||"Прочее"),amount,note:String(f.get("note")||""),userId:u.id}});go("finance","Расход записан")}
export async function ingredientAction(f:FormData){await requireOwner();const ingredientId=n(f.get("ingredientId")),quantity=n(f.get("quantity"));if(quantity<=0)throw new Error("Введите количество");await db.$transaction([db.ingredient.update({where:{id:ingredientId},data:{stock:{increment:quantity}}}),db.ingredientMovement.create({data:{ingredientId,quantity,type:"PURCHASE",note:String(f.get("note")||"Приход сырья")}})]);go("ingredients","Приход добавлен")}
export async function customerAction(f:FormData){await requireBusinessWriter();await db.customer.create({data:{name:String(f.get("name")||""),phone:String(f.get("phone")||""),address:String(f.get("address")||""),creditLimit:n(f.get("creditLimit"))}});go("customers","Клиент добавлен")}
export async function productAction(f:FormData){await requireOwner();const p=await db.product.create({data:{name:String(f.get("name")||""),sku:String(f.get("sku")||""),price:n(f.get("price")),costPrice:n(f.get("costPrice")),stock:{create:{quantity:0}}}});go("products","Продукт "+p.name+" добавлен")}
async function recalculateProductCost(productId:number){const rows=await db.recipeItem.findMany({where:{productId},include:{ingredient:true}});const cost=rows.reduce((sum,r)=>sum+r.quantity*r.ingredient.purchasePrice,0);await db.product.update({where:{id:productId},data:{costPrice:Math.round(cost*100000)/100000}})}export async function recipeAction(f:FormData){await requireOwner();const productId=n(f.get("productId"));await db.recipeItem.upsert({where:{productId_ingredientId:{productId,ingredientId:n(f.get("ingredientId"))}},create:{productId,ingredientId:n(f.get("ingredientId")),quantity:n(f.get("quantity"))},update:{quantity:n(f.get("quantity"))}});await recalculateProductCost(productId);go("recipes","Рецептура и себестоимость обновлены")}
export async function deleteRecipeItemAction(f:FormData){await requireOwner();const id=n(f.get("id"));const item=await db.recipeItem.findUniqueOrThrow({where:{id}});await db.recipeItem.delete({where:{id}});await recalculateProductCost(item.productId);go("recipes","Ингредиент удалён из рецепта, себестоимость пересчитана")}
export async function createIngredientAction(f:FormData){
 await requireOwner();
 const name=String(f.get("name")||"").trim(),unit=String(f.get("unit")||"KG") as "KG"|"G"|"L"|"ML"|"PCS",stock=n(f.get("stock")),minStock=n(f.get("minStock")),purchasePrice=n(f.get("purchasePrice"));
 if(!name)throw new Error("Введите название сырья");if(stock<0||minStock<0||purchasePrice<0)throw new Error("Значения не могут быть отрицательными");
 await db.$transaction(async tx=>{const item=await tx.ingredient.create({data:{name,unit,stock,minStock,targetStock:n(f.get("targetStock")),purchasePrice}});if(stock>0)await tx.ingredientMovement.create({data:{ingredientId:item.id,type:"ADJUSTMENT",quantity:stock,note:"Начальный остаток"}})});
 go("ingredients","Новое сырьё добавлено")
}
export async function updateIngredientAction(f:FormData){
 await requireOwner();const id=n(f.get("id")),name=String(f.get("name")||"").trim(),unit=String(f.get("unit")||"KG") as "KG"|"G"|"L"|"ML"|"PCS",minStock=n(f.get("minStock")),purchasePrice=n(f.get("purchasePrice"));
 if(!name||minStock<0||purchasePrice<0)throw new Error("Проверьте данные сырья");
 const before=await db.ingredient.findUniqueOrThrow({where:{id},include:{recipes:true}});if(before.unit!==unit&&before.recipes.length)throw new Error("Единицу сырья из рецепта менять нельзя — создайте новую позицию");
 await db.ingredient.update({where:{id},data:{name,unit,minStock,targetStock:n(f.get("targetStock")),purchasePrice}});for(const productId of new Set(before.recipes.map(r=>r.productId)))await recalculateProductCost(productId);go("ingredients","Карточка и себестоимость обновлены")
}export async function adjustIngredientAction(f:FormData){
 await requireOwner();const id=n(f.get("id")),actual=n(f.get("actual"));if(actual<0)throw new Error("Остаток не может быть отрицательным");
 await db.$transaction(async tx=>{const item=await tx.ingredient.findUniqueOrThrow({where:{id}}),delta=actual-item.stock;await tx.ingredient.update({where:{id},data:{stock:actual}});await tx.ingredientMovement.create({data:{ingredientId:id,type:"ADJUSTMENT",quantity:delta,note:String(f.get("note")||"Инвентаризация")}})});go("ingredients","Фактический остаток сохранён")
}
export async function toggleIngredientAction(f:FormData){
 await requireOwner();const id=n(f.get("id")),item=await db.ingredient.findUniqueOrThrow({where:{id}});await db.ingredient.update({where:{id},data:{active:!item.active}});go("ingredients",item.active?"Сырьё перенесено в архив":"Сырьё восстановлено")
}
export async function returnShipmentItemAction(f:FormData){
 const u=await requireBusinessWriter(),shipmentId=n(f.get("shipmentId")),productId=n(f.get("productId")),quantity=n(f.get("quantity"));if(quantity<=0)throw new Error("Введите количество возврата");
 await db.$transaction(async tx=>{const line=await tx.shipmentItem.findFirst({where:{shipmentId,productId}});if(!line)throw new Error("Позиция не найдена в накладной");const returned=await tx.productMovement.aggregate({_sum:{quantity:true},where:{shipmentId,productId,type:"RETURN"}}),already=returned._sum.quantity||0;if(already+quantity>line.quantity)throw new Error("Возврат больше отгруженного количества");await tx.productStock.update({where:{productId},data:{quantity:{increment:quantity}}});await tx.productMovement.create({data:{productId,type:"RETURN",quantity,userId:u.id,shipmentId,note:String(f.get("note")||"Возврат от клиента")}});await tx.shipment.update({where:{id:shipmentId},data:{total:{decrement:line.price*quantity}}})});go("shipments","Возврат принят на склад")
}
export async function writeOffProductAction(f:FormData){
 const u=await requireOwner(),productId=n(f.get("productId")),quantity=n(f.get("quantity"));if(quantity<=0)throw new Error("Введите количество списания");
 await db.$transaction(async tx=>{const stock=await tx.productStock.findUniqueOrThrow({where:{productId}});if(stock.quantity<quantity)throw new Error("Недостаточно продукции на складе");await tx.productStock.update({where:{productId},data:{quantity:{decrement:quantity}}});await tx.productMovement.create({data:{productId,type:"WRITE_OFF",quantity:-quantity,userId:u.id,note:String(f.get("note")||"Порча / списание")}})});go("stock","Списание готовой продукции записано")
}
export async function updateProductAction(f:FormData){await requireOwner();const id=n(f.get("id")),name=String(f.get("name")||"").trim(),sku=String(f.get("sku")||"").trim(),price=n(f.get("price"));if(!name||!sku||price<0)throw new Error("Проверьте данные продукции");await db.product.update({where:{id},data:{name,sku,price}});go("products","Продукция обновлена")}
export async function toggleProductAction(f:FormData){await requireOwner();const id=n(f.get("id")),p=await db.product.findUniqueOrThrow({where:{id}});await db.product.update({where:{id},data:{active:!p.active}});go("products",p.active?"Продукция архивирована":"Продукция восстановлена")}
export async function updateCustomerAction(f:FormData){await requireOwner();const id=n(f.get("id")),name=String(f.get("name")||"").trim();if(!name)throw new Error("Введите название клиента");await db.customer.update({where:{id},data:{name,phone:String(f.get("phone")||""),address:String(f.get("address")||""),creditLimit:n(f.get("creditLimit"))}});go("customers","Клиент обновлён")}
export async function toggleCustomerAction(f:FormData){await requireOwner();const id=n(f.get("id")),c=await db.customer.findUniqueOrThrow({where:{id}});await db.customer.update({where:{id},data:{active:!c.active}});go("customers",c.active?"Клиент архивирован":"Клиент восстановлен")}
export async function createSupplierAction(f:FormData){await requireOwner();const name=String(f.get("name")||"").trim();if(!name)throw new Error("Введите поставщика");await db.supplier.create({data:{name,phone:String(f.get("phone")||""),address:String(f.get("address")||""),note:String(f.get("note")||"")}});go("suppliers","Поставщик добавлен")}
export async function updateSupplierAction(f:FormData){await requireOwner();const id=n(f.get("id")),name=String(f.get("name")||"").trim();if(!name)throw new Error("Введите поставщика");await db.supplier.update({where:{id},data:{name,phone:String(f.get("phone")||""),address:String(f.get("address")||""),note:String(f.get("note")||"")}});go("suppliers","Поставщик обновлён")}
export async function toggleSupplierAction(f:FormData){await requireOwner();const id=n(f.get("id")),s=await db.supplier.findUniqueOrThrow({where:{id}});await db.supplier.update({where:{id},data:{active:!s.active}});go("suppliers",s.active?"Поставщик архивирован":"Поставщик восстановлен")}
export async function addSupplierDebtAction(f:FormData){await requireOwner();const supplierId=n(f.get("supplierId")),amount=n(f.get("amount")),rawDate=String(f.get("debtDate")||""),debtDate=rawDate?new Date(rawDate+"T12:00:00"):new Date(),note=String(f.get("note")||"Долг поставщику");if(amount<=0||Number.isNaN(debtDate.getTime()))throw new Error("Проверьте поставщика, сумму и дату");await db.supplierDebt.create({data:{supplierId,amount,debtDate,note}});go("suppliers","Долг поставщику добавлен")}
export async function paySupplierAction(f:FormData){await requireOwner();const supplierId=n(f.get("supplierId")),amount=n(f.get("amount")),method=String(f.get("method"))==="TRANSFER"?"TRANSFER" as const:"CASH" as const,note=String(f.get("note")||"");if(amount<=0)throw new Error("Введите сумму оплаты");await db.$transaction(async tx=>{let left=amount;const debts=await tx.supplierDebt.findMany({where:{supplierId},orderBy:{debtDate:"asc"}});const outstanding=debts.reduce((s,d)=>s+Math.max(0,d.amount-d.paidAmount),0);if(amount>outstanding+.00001)throw new Error("Оплата больше текущего долга поставщику");for(const d of debts){if(left<=0)break;const due=Math.max(0,d.amount-d.paidAmount);if(!due)continue;const part=Math.min(due,left);await tx.supplierDebt.update({where:{id:d.id},data:{paidAmount:{increment:part}}});await tx.supplierPayment.create({data:{supplierId,supplierDebtId:d.id,amount:part,method,note}});left-=part}});go("suppliers","Оплата поставщику записана")}
export async function purchaseAction(f:FormData){
 const u=await requireOwner(),supplierId=n(f.get("supplierId")),invoiceNumber=String(f.get("invoiceNumber")||""),note=String(f.get("note")||"");let items:{ingredientId:number;quantity:number;price:number}[]=[];
 try{items=JSON.parse(String(f.get("items")||"[]"))}catch{throw new Error("Не удалось прочитать закупку")}
 if(!items.length||items.some(i=>i.quantity<=0||i.price<0)||new Set(items.map(i=>i.ingredientId)).size!==items.length)throw new Error("Проверьте позиции закупки");
 await db.$transaction(async tx=>{const ingredients=await tx.ingredient.findMany({where:{id:{in:items.map(i=>i.ingredientId)}}});if(ingredients.length!==items.length)throw new Error("Сырьё не найдено");const total=items.reduce((s,i)=>s+i.quantity*i.price,0);const purchase=await tx.purchase.create({data:{supplierId,userId:u.id,invoiceNumber,total,note,items:{create:items}}});for(const item of items){const old=ingredients.find(i=>i.id===item.ingredientId)!;const newStock=old.stock+item.quantity,newPrice=newStock?((old.stock*old.purchasePrice)+(item.quantity*item.price))/newStock:item.price;await tx.ingredient.update({where:{id:item.ingredientId},data:{stock:{increment:item.quantity},purchasePrice:Math.round(newPrice*100000)/100000}});await tx.ingredientMovement.create({data:{ingredientId:item.ingredientId,type:"PURCHASE",quantity:item.quantity,note:"Закупка №"+purchase.id+(invoiceNumber?" · "+invoiceNumber:"")}})}});
 const productIds=await db.recipeItem.findMany({where:{ingredientId:{in:items.map(i=>i.ingredientId)}},select:{productId:true}});for(const id of new Set(productIds.map(x=>x.productId)))await recalculateProductCost(id);go(String(f.get("returnTab"))==="procurement"?"procurement":"suppliers","Закупка проведена, сырьё оприходовано")
}
export async function createUserAction(f:FormData){await requireOwner();const name=String(f.get("name")||"").trim(),username=String(f.get("username")||"").trim(),password=String(f.get("password")||"");if(!name||!username||password.length<6)throw new Error("Заполните данные, пароль минимум 6 символов");await db.user.create({data:{name,username,passwordHash:await hash(password,10),role:String(f.get("role"))==="OWNER"?"OWNER":String(f.get("role"))==="INVESTOR"?"INVESTOR":"WORKER"}});go("team","Сотрудник добавлен")}
export async function updateUserAction(f:FormData){const owner=await requireOwner(),id=n(f.get("id"));if(id===owner.id&&String(f.get("active"))==="false")throw new Error("Нельзя отключить собственную учётную запись");await db.user.update({where:{id},data:{name:String(f.get("name")||"").trim(),role:String(f.get("role"))==="OWNER"?"OWNER":String(f.get("role"))==="INVESTOR"?"INVESTOR":"WORKER"}});go("team","Данные сотрудника обновлены")}
export async function toggleUserAction(f:FormData){const owner=await requireOwner(),id=n(f.get("id"));if(id===owner.id)throw new Error("Нельзя отключить себя");const u=await db.user.findUniqueOrThrow({where:{id}});await db.user.update({where:{id},data:{active:!u.active}});go("team",u.active?"Доступ сотрудника отключён":"Доступ сотрудника восстановлен")}
export async function resetUserPasswordAction(f:FormData){await requireOwner();const password=String(f.get("password")||"");if(password.length<6)throw new Error("Пароль минимум 6 символов");await db.user.update({where:{id:n(f.get("id"))},data:{passwordHash:await hash(password,10)}});go("team","Пароль сотрудника изменён")}
export async function changeOwnPasswordAction(f:FormData){const u=await requireUser(),current=String(f.get("current")||""),password=String(f.get("password")||""),row=await db.user.findUniqueOrThrow({where:{id:u.id}});if(!await compare(current,row.passwordHash))throw new Error("Текущий пароль неверен");if(password.length<6)throw new Error("Новый пароль минимум 6 символов");await db.user.update({where:{id:u.id},data:{passwordHash:await hash(password,10)}});go("team","Ваш пароль изменён")}
