"use client";
import Link from"next/link";import{useMemo,useState}from"react";import{Check,PackageCheck,ShoppingCart,TriangleAlert}from"lucide-react";import{purchaseAction}from"@/app/actions";
type Supply={id:number;name:string;unit:string;stock:number;minStock:number;targetStock:number;price:number};
type Row=Supply&{selected:boolean;quantity:number};
export default function SupplyMobile({items,suppliers}:{items:Supply[];suppliers:{id:number;name:string}[]}){
 const[rows,setRows]=useState<Row[]>(items.map(x=>({...x,selected:true,quantity:Number(Math.max(.001,(x.targetStock||x.minStock*2)-x.stock).toFixed(3))})));
 const chosen=rows.filter(r=>r.selected),total=useMemo(()=>chosen.reduce((s,r)=>s+r.quantity*r.price,0),[chosen]);
 const patch=(id:number,data:Partial<Row>)=>setRows(rows.map(r=>r.id===id?{...r,...data}:r));
 if(!items.length)return <section className="supplyEmpty"><PackageCheck size={44}/><h2>Закупки не требуются</h2><p>Все активные остатки выше минимального уровня.</p></section>;
 return <form action={purchaseAction} className="supplyMobile"><input type="hidden" name="returnTab" value="procurement"/><header className="supplySummary"><div><p className="eyebrow">СПИСОК НА РЫНОК</p><h2>{chosen.length} позиций</h2><span>Ориентировочно {total.toFixed(2)} с.</span></div><ShoppingCart size={34}/></header><div className="supplyFilters"><span className="supplyPill zero">{items.filter(x=>x.stock<=0).length} закончилось</span><span className="supplyPill low">{items.filter(x=>x.stock>0&&x.stock<=x.minStock).length} мало</span></div><div className="supplyList">{rows.sort((a,b)=>(a.stock>0?1:0)-(b.stock>0?1:0)).map(r=><article className={"supplyRow "+(r.selected?"selected":"")} key={r.id}><button type="button" className="supplyCheck" aria-label={r.selected?"Убрать из списка":"Добавить в список"} onClick={()=>patch(r.id,{selected:!r.selected})}>{r.selected&&<Check size={17}/>}</button><div className="supplyInfo"><div className="supplyName"><b>{r.name}</b>{r.stock<=0?<span className="stockZero">НЕТ</span>:<span className="stockLow"><TriangleAlert size={12}/>МАЛО</span>}</div><small>Сейчас: <strong>{r.stock.toFixed(3)} {r.unit}</strong> · минимум {r.minStock} · цель {r.targetStock||r.minStock*2}</small></div><label>Купить<input type="number" min=".001" step=".001" value={r.quantity} disabled={!r.selected} onChange={e=>patch(r.id,{quantity:Number(e.target.value)})}/><em>{r.unit}</em></label><label>Цена<input type="number" min="0" step=".001" value={r.price} disabled={!r.selected} onChange={e=>patch(r.id,{price:Number(e.target.value)})}/><em>с.</em></label></article>)}</div>{suppliers.length?<div className="supplyCheckout"><label>Где покупаем<select name="supplierId">{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Номер чека / накладной<input name="invoiceNumber" placeholder="Можно оставить пустым"/></label><label>Примечание<input name="note" defaultValue="Закупка снабженца"/></label><input type="hidden" name="items" value={JSON.stringify(chosen.map(r=>({ingredientId:r.id,quantity:r.quantity,price:r.price})))}/><div className="supplyTotal"><span>Итого ориентировочно</span><strong>{total.toFixed(2)} с.</strong></div><button disabled={!chosen.length}><ShoppingCart size={18}/>Купил — оприходовать</button></div>:<div className="supplyNoSupplier"><p>Сначала добавьте рынок или поставщика.</p><Link href="/?tab=suppliers">Добавить поставщика</Link></div>}</form>
}